# This file is a template, and might need editing before it works on your project.
stages:
  - build
  - pycodestyle checker
  - test

docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

code-checker:
  stage: pycodestyle checker
  script:
    - python -m pycodestyle .


unittest:
  stage: test
  script:
    - python3 -m unittest discover -s test -p "*_test.py"
